import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "Movie Stream Dashbaord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="us">
      <StoreProvider>
      <body>
            {children}
          </body>
      </StoreProvider>
    </html>
  );
}

