import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import SessionWrapper from "./SessionWrapper";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Movie Stream Dashbaord",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ["latin"],variable: "--font-roboto", weight: ["400", "500", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="us">
      <SessionWrapper>
        <StoreProvider>
          <body className={roboto.className}> 
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </body>
        </StoreProvider>
      </SessionWrapper>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import StoreProvider from "./StoreProvider";
// import SessionWrapper from "./SessionWrapper";
// import { ToastProvider } from "./ToastProvider";

// export const metadata: Metadata = {
//   title: "Movie Stream Dashboard",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="us">
//       <body>
//         <SessionWrapper>
//           <StoreProvider>
//             {children}
//             <ToastProvider />
//           </StoreProvider>
//         </SessionWrapper>
//       </body>
//     </html>
//   );
// }
